version: "3.8"

services:
  bot:
    build:
      context: .
      network: host
    image: morgen-bot-local:latest
    container_name: morgen_bot
    restart: unless-stopped
    network_mode: host
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./data:/app/data
