version: "3.8"

services:
  bot:
    image: ghcr.io/gorlix/morgencalendar-telegram-bot:latest
    container_name: morgen_bot
    restart: unless-stopped
    # network_mode: host
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ENCRYPTION_MASTER_KEY=${ENCRYPTION_MASTER_KEY}
    volumes:
      - ./data:/app/data
